#
# Vivado (TM) v2015.4 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'project_gpr'
#
# Generated by Vivado on Tue Oct 18 10:25:30 PDT 2016
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/ram_2port.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_short.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop2.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_bram.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/x300_zpu_config.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/core/zpu_config.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/core/zpupkg.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/wishbone/wishbone_pkg.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/zpu_top_pkg.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_waveform_datamover/axi_waveform_datamover.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/setting_reg.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_parser.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_framer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/clip.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_4k_2clk/fifo_4k_2clk.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_short_2clk/fifo_short_2clk.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/wishbone/zpu_wb_bridge.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/core/zpu_core.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/settings_readback.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/settings_bus.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/meta_sync_single.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/ioport2_msg_codec.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_defines.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_bit_ctrl.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_mem_xilinx_block.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_mem_small.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_mem_medium.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_fifo_ctrl.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/xfft_short_32b/xfft_short_32b.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/xfft_short_16b/xfft_short_16b.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/SP_DDS/SP_DDS.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/mult_gen_32b/mult_gen_32b.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/bram_stream_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/vita/packet_error_responder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/vita/flow_control_responder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_cascade.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/add2_and_clip.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/wishbone/zpu_system.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/simple_uart_tx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/simple_uart_rx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_axi_wb_conv.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/meta_sync.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/ip_hdr_checksum.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_byte_ctrl.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/defines.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/fix_short_packet.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/delay_line.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/crc.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/address_filter_promisc.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/address_filter.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/waveform_stream.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/waveform_formatter.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/waveform_dds.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/sq_mag_estimate.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/peak_finder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/freq_domain_lpf.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/fifo_generator_adc/fifo_generator_adc.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/fft_corr.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/cmpy_16b/cmpy_16b.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/CHIRP_DDS.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/adc_data_axis_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/timing/time_compare.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_responder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_encoder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_fifo_large.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/source_flow_control.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_packet_gate.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/sign_extend.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/round.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/add2_and_clip_reg.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/synchronizer_impl.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/simple_spi_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_crossclock.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/gpio_atr.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux4.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/bootram/bootram.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/zpu_wb_top.vhd"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/zpu/zpu_bootram.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/wishbone_if.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/wb_1master.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_hold_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/utils.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/CRC32_D8.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/CRC32_D64.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_enqueue.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_dequeue.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_data_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/sync_clk_xgmii_tx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/sync_clk_wb.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/simple_uart.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac_tx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac_rx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_hold_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_enqueue.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_dequeue.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_data_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_wb_reg_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_top.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/flow_ctrl_tx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/fault_sm.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/eth_dispatch.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/chdr_eth_framer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wishbone/axi_stream_to_wb.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/axi_slave_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/axi_forwarding_cam.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/wavegen_block.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_sample_synchronizer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_pulse_controller.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/matched_filter_range_detector.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_output_port.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_input_port.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cmd_pkt_proc.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_deframer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_packet_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/rx_control_gen3.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/radio_core_regs.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/db_control.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk_cascade.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux4.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/round_sd.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/synchronizer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_extract_tlast.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_embed_tlast.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_defs.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_dma_master.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_chdr_test_pattern.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/reset_sync.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/xge_mac.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge_interface/xge_handshake.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge_interface/xge64_to_axi64.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/rxmac_to_ll8.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_pkt_route_specifier.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/mdio.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/ll8_to_txmac.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/ll8_to_axi64.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/flow_ctrl_rx.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/eth_interface.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/axi_crossbar.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge_interface/axi_count_packets_in_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge_interface/axi64_to_xge64.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/axi64_to_ll8.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_core_regs.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/timing/timekeeper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell_regs.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cordic.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/rx_dcoffset.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/dsp/clip_reg.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_dma_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/soft_ctrl.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1.ngc"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/aurora_64b66b_pcs_pma/aurora_64b66b_pcs_pma.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/ten_gig_eth_pcs_pma/ten_gig_eth_pcs_pma.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge_interface/xge_mac_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_lossy_samp_gate.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_iop2_msg_arbiter.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_dma_ctrl.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_basic_regs.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/data_swapper_64.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/cvita_dechunker.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/cvita_chunker.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_cap_gen/cap_pattern_verifier.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux8.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux8.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/axi_dma_fifo_block.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axis_interconnect_1s2m/axis_interconnect_1s2m.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axis_interconnect_1m2s/axis_interconnect_1m2s.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_block.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/timing/pps_synchronizer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/tx_frontend_gen3.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/rx_frontend_gen3.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/ten_gig_eth_pcs_pma/ten_gige_phy.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/one_gig_eth_pcs_pma/one_gige_phy.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/aurora_64b66b_pcs_pma/aurora_phy_x1.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/aurora_64b66b_pcs_pma/aurora_axis_mac.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/bus_int.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/axi_intercon_2x64_128/axi_intercon_2x64_128.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/x300_gpr_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/timing/pps_generator.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/LvFpga_Chinch_Interface.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/LvFpga_Chinch_Interface.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/io_port2/LvFpga_Chinch_Interface.ngc"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/por_gen.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/gpio_atr_io.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/x300_sfpp_io_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/x300_pcie_int.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/gen_ddrlvds.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/capture_ddrlvds.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/ddr3_32bit.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/pcie_clk_gen/pcie_clk_gen.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/bus_clk_gen/bus_clk_gen.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/radio_clk_gen/radio_clk_gen.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/x300_gpr.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/include/rx_cmd_1s4m_ic.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/rx_cmd_1s4m_axis_interconnect/rx_cmd_1s4m_axis_interconnect.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axis_interconnect_1m2s/axis_interconnect_1m2s.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axis_interconnect_1s2m/axis_interconnect_1s2m.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/mig_7series_1/mig_7series_1.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/peak_axis_clock_converter/peak_axis_clock_converter.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/peak_axis_dwidth_converter/peak_axis_dwidth_converter.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/fifo_generator_adc/fifo_generator_adc.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/SP_DDS/SP_DDS.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_waveform_datamover/axi_waveform_datamover.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/cmpy_16b/cmpy_16b.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/ethernet_rgmii/ethernet_rgmii.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/ethernet_tx_axis_interconnect/ethernet_tx_axis_interconnect.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/mixer_mult_gen/mixer_mult_gen.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/mult_gen_32b/mult_gen_32b.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/xfft_0/xfft_0.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/xfft_short_16b/xfft_short_16b.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/xfft_short_32b/xfft_short_32b.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/timescale.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/utils.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/timescale.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/defines.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/CRC32_D8.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/CRC32_D64.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/wb_spi/rtl/verilog/spi_defines.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/simple_gemac/eth_tasks.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/data_types.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/coregen/simple_fir.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_lite_slave.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_default_inst_x310.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_default_inst_x300.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_auto_inst_x310.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_auto_inst_x300.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/ddr3_32bit_mig_sim_parameters.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/ddr3_32bit_mig_parameters.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_4.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_3.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3_reload_addrfilt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2filt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto_HALFBAND_CENTRE0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto0_2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto0_1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto0_0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2_reload_addrfilt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1filt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto_HALFBAND_CENTRE0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto0_2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto0_1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto0_0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1_reload_addrfilt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3filt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3COEFF_auto_HALFBAND_CENTRE0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3COEFF_auto0_1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3COEFF_auto0_0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3_reload_addrfilt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2filt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto_HALFBAND_CENTRE0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto0_2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto0_1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto0_0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2_reload_addrfilt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1filt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto_HALFBAND_CENTRE0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_5.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_4.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_3.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_2.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1_reload_addrfilt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3filt_decode_rom.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto_HALFBAND_CENTRE0.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_5.mif"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/mig_a.prj"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/bootram/bootram.coe"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/axi/axi_chdr_tb.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/control/axi_crossbar/sim_2x2/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/control/axi_crossbar/sim_4x4/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/control/axi_crossbar/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/dsp/ddc_chain/dc_in_cordic_decim_2/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/dsp/ddc_chain/dc_in_cordic_decim_6/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/fifo/axi_dram_fifo/sim_sram_1/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/fifo/axi_dram_fifo/sim_sram_2/simulation_script.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/sim/packet_proc/eth_dispatch/simulation_script.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project project_gpr ./project_gpr

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects project_gpr]
set_property "corecontainer.enable" "1" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "part" "xc7k325tffg900-2" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/ram_2port.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_short.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop2.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_bram.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/x300_zpu_config.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/core/zpu_config.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/core/zpupkg.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/wishbone/wishbone_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/zpu_top_pkg.vhd"]"\
 "[file normalize "$origin_dir/../../ip/axi_waveform_datamover/axi_waveform_datamover.xci"]"\
 "[file normalize "$origin_dir/../../ip/axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/setting_reg.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_parser.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_framer.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/clip.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_4k_2clk/fifo_4k_2clk.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_short_2clk/fifo_short_2clk.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/wishbone/zpu_wb_bridge.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/core/zpu_core.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/settings_readback.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/settings_bus.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/meta_sync_single.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/ioport2_msg_codec.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_defines.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_bit_ctrl.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_mem_xilinx_block.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_mem_small.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_mem_medium.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_fifo_ctrl.v"]"\
 "[file normalize "$origin_dir/../../ip/xfft_short_32b/xfft_short_32b.xci"]"\
 "[file normalize "$origin_dir/../../ip/xfft_short_16b/xfft_short_16b.xci"]"\
 "[file normalize "$origin_dir/../../ip/SP_DDS/SP_DDS.xci"]"\
 "[file normalize "$origin_dir/../../ip/mult_gen_32b/mult_gen_32b.xci"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/bram_stream_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/vita/packet_error_responder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/vita/flow_control_responder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_cascade.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/add2_and_clip.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/wishbone/zpu_system.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/simple_uart_tx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/simple_uart_rx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_axi_wb_conv.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/meta_sync.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/ip_hdr_checksum.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_byte_ctrl.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/defines.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/generic_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/fix_short_packet.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/delay_line.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/crc.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/address_filter_promisc.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/address_filter.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/waveform_stream.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/waveform_formatter.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/waveform_dds.v"]"\
 "[file normalize "$origin_dir/../../source/top/sq_mag_estimate.v"]"\
 "[file normalize "$origin_dir/../../source/top/peak_finder.v"]"\
 "[file normalize "$origin_dir/../../source/top/freq_domain_lpf.v"]"\
 "[file normalize "$origin_dir/../../ip/fifo_generator_adc/fifo_generator_adc.xci"]"\
 "[file normalize "$origin_dir/../../source/top/fft_corr.v"]"\
 "[file normalize "$origin_dir/../../ip/cmpy_16b/cmpy_16b.xci"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/CHIRP_DDS.vhd"]"\
 "[file normalize "$origin_dir/../../source/top/adc_data_axis_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/timing/time_compare.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_responder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_encoder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_fifo_large.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/source_flow_control.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_packet_gate.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/sign_extend.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/round.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/add2_and_clip_reg.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/synchronizer_impl.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/simple_spi_core.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_crossclock.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/gpio_atr.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux4.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/bootram/bootram.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/zpu_wb_top.vhd"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/zpu/zpu_bootram.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/wishbone_if.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/wb_1master.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_hold_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/utils.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/CRC32_D8.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/CRC32_D64.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_enqueue.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_dequeue.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/tx_data_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/sync_clk_xgmii_tx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/sync_clk_wb.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/simple_uart.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac_tx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac_rx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_hold_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_enqueue.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_dequeue.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/rx_data_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_wb_reg_core.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/i2c_master_top.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/flow_ctrl_tx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/fault_sm.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/eth_dispatch.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/chdr_eth_framer.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wishbone/axi_stream_to_wb.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/axi_slave_mux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/axi_forwarding_cam.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/wavegen_block.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_sample_synchronizer.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_pulse_controller.v"]"\
 "[file normalize "$origin_dir/../../source/top/matched_filter_range_detector.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_output_port.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_input_port.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cmd_pkt_proc.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_deframer.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_packet_mux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/rx_control_gen3.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/radio_core_regs.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/db_control.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk_cascade.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux4.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/round_sd.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/synchronizer.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_extract_tlast.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_embed_tlast.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_defs.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_dma_master.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_chdr_test_pattern.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/reset_sync.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/xge_mac.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge_interface/xge_handshake.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge_interface/xge64_to_axi64.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/rxmac_to_ll8.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_pkt_route_specifier.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/mdio.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/ll8_to_txmac.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/ll8_to_axi64.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/flow_ctrl_rx.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/eth_interface.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/axi_crossbar.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge_interface/axi_count_packets_in_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge_interface/axi64_to_xge64.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/axi64_to_ll8.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_core_regs.vh"]"\
 "[file normalize "$origin_dir/../../source/top/radar_core.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/timing/timekeeper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell_regs.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cordic.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/rx_dcoffset.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/dsp/clip_reg.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_mux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_dma_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/soft_ctrl.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1.ngc"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/axi64_8k_2clk_fifo/axi64_8k_2clk_fifo.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/aurora_64b66b_pcs_pma/aurora_64b66b_pcs_pma.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/axi64_4k_2clk_fifo/axi64_4k_2clk_fifo.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/ten_gig_eth_pcs_pma/ten_gig_eth_pcs_pma.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge_interface/xge_mac_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/simple_gemac_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_lossy_samp_gate.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_iop2_msg_arbiter.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_dma_ctrl.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/pcie_basic_regs.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/data_swapper_64.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/cvita_dechunker.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/cvita_chunker.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_cap_gen/cap_pattern_verifier.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux8.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux8.v"]"\
 "[file normalize "$origin_dir/../../ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.xci"]"\
 "[file normalize "$origin_dir/../../source/top/axi_dma_fifo_block.v"]"\
 "[file normalize "$origin_dir/../../ip/axis_interconnect_1s2m/axis_interconnect_1s2m.xci"]"\
 "[file normalize "$origin_dir/../../ip/axis_interconnect_1m2s/axis_interconnect_1m2s.xci"]"\
 "[file normalize "$origin_dir/../../source/top/radar_block.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/timing/pps_synchronizer.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/tx_frontend_gen3.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/rx_frontend_gen3.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/ten_gig_eth_pcs_pma/ten_gige_phy.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/one_gig_eth_pcs_pma/one_gige_phy.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/aurora_64b66b_pcs_pma/aurora_phy_x1.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/aurora_64b66b_pcs_pma/aurora_axis_mac.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/bus_int.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/axi_intercon_2x64_128/axi_intercon_2x64_128.xci"]"\
 "[file normalize "$origin_dir/../../source/top/x300_gpr_core.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/timing/pps_generator.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/LvFpga_Chinch_Interface.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/LvFpga_Chinch_Interface.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/io_port2/LvFpga_Chinch_Interface.ngc"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/por_gen.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/gpio_atr_io.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/x300_sfpp_io_core.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/x300_pcie_int.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/gen_ddrlvds.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/capture_ddrlvds.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/ddr3_32bit.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/pcie_clk_gen/pcie_clk_gen.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/bus_clk_gen/bus_clk_gen.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/radio_clk_gen/radio_clk_gen.xci"]"\
 "[file normalize "$origin_dir/../../source/top/x300_gpr.v"]"\
 "[file normalize "$origin_dir/../../source/include/rx_cmd_1s4m_ic.v"]"\
 "[file normalize "$origin_dir/../../ip/rx_cmd_1s4m_axis_interconnect/rx_cmd_1s4m_axis_interconnect.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/axis_interconnect_1m2s/axis_interconnect_1m2s.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/axis_interconnect_1s2m/axis_interconnect_1s2m.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/mig_7series_1/mig_7series_1.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/peak_axis_clock_converter/peak_axis_clock_converter.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/peak_axis_dwidth_converter/peak_axis_dwidth_converter.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/fifo_generator_adc/fifo_generator_adc.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/SP_DDS/SP_DDS.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/axi_waveform_datamover/axi_waveform_datamover.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/cmpy_16b/cmpy_16b.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/ethernet_rgmii/ethernet_rgmii.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/ethernet_tx_axis_interconnect/ethernet_tx_axis_interconnect.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/mixer_mult_gen/mixer_mult_gen.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/mult_gen_32b/mult_gen_32b.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/xfft_0/xfft_0.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/xfft_short_16b/xfft_short_16b.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/xfft_short_32b/xfft_short_32b.upgrade_log"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/verilog/timescale.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/utils.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/timescale.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/defines.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/CRC32_D8.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/xge/rtl/include/CRC32_D64.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/wb_spi/rtl/verilog/spi_defines.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/simple_gemac/eth_tasks.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/data_types.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/coregen/simple_fir.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_lite_slave.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_default_inst_x310.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_default_inst_x300.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_auto_inst_x310.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/rfnoc_ce_auto_inst_x300.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/ddr3_32bit_mig_sim_parameters.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/ddr3_32bit_mig_parameters.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_4.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_3.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3_reload_addrfilt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2filt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto_HALFBAND_CENTRE0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto0_2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto0_1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2COEFF_auto0_0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2_reload_addrfilt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1filt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto_HALFBAND_CENTRE0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto0_2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto0_1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1COEFF_auto0_0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1_reload_addrfilt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3filt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3COEFF_auto_HALFBAND_CENTRE0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3COEFF_auto0_1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3COEFF_auto0_0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3_reload_addrfilt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec3.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2filt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto_HALFBAND_CENTRE0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto0_2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto0_1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2COEFF_auto0_0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2_reload_addrfilt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1filt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto_HALFBAND_CENTRE0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_5.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_4.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_3.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_2.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1COEFF_auto0_0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1_reload_addrfilt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbdec1.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3filt_decode_rom.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto_HALFBAND_CENTRE0.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/coregen_dsp/hbint3COEFF_auto0_5.mif"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/ddr3_32bit/mig_a.prj"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/bootram/bootram.coe"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "x300/x300_zpu_config.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "core/zpu_config.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "core/zpupkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "wishbone/wishbone_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "zpu/zpu_top_pkg.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "wishbone/zpu_wb_bridge.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "core/zpu_core.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "wishbone/zpu_system.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "wavegen/CHIRP_DDS.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "zpu/zpu_wb_top.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "VHDL" $file_obj

set file "radio/radio_core_regs.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "top/radar_core_regs.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "rfnoc/noc_shell_regs.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "coregen_dsp/hbdec1.ngc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "io_port2/LvFpga_Chinch_Interface.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "io_port2/LvFpga_Chinch_Interface.ngc"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "NGC" $file_obj

set file "rx_cmd_1s4m_axis_interconnect/rx_cmd_1s4m_axis_interconnect.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "axi_vfifo_ctrl_0/axi_vfifo_ctrl_0.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "axis_interconnect_1m2s/axis_interconnect_1m2s.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "axis_interconnect_1s2m/axis_interconnect_1s2m.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "mig_7series_1/mig_7series_1.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "peak_axis_clock_converter/peak_axis_clock_converter.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "peak_axis_dwidth_converter/peak_axis_dwidth_converter.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "fifo_generator_adc/fifo_generator_adc.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "SP_DDS/SP_DDS.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "axi_waveform_datamover/axi_waveform_datamover.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "cmpy_16b/cmpy_16b.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "ethernet_rgmii/ethernet_rgmii.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "ethernet_tx_axis_interconnect/ethernet_tx_axis_interconnect.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "mixer_mult_gen/mixer_mult_gen.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "mult_gen_32b/mult_gen_32b.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "xfft_0/xfft_0.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "xfft_short_16b/xfft_short_16b.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "xfft_short_32b/xfft_short_32b.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj

set file "rfnoc/data_types.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "coregen/simple_fir.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "ddr3_32bit/ddr3_32bit_mig_sim_parameters.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "ddr3_32bit/ddr3_32bit_mig_parameters.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj

set file "coregen_dsp/hbint3COEFF_auto0_4.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3COEFF_auto0_3.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3COEFF_auto0_2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3COEFF_auto0_1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3COEFF_auto0_0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3_reload_addrfilt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2filt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2COEFF_auto_HALFBAND_CENTRE0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2COEFF_auto0_2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2COEFF_auto0_1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2COEFF_auto0_0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2_reload_addrfilt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1filt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1COEFF_auto_HALFBAND_CENTRE0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1COEFF_auto0_2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1COEFF_auto0_1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1COEFF_auto0_0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1_reload_addrfilt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec3filt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec3COEFF_auto_HALFBAND_CENTRE0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec3COEFF_auto0_1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec3COEFF_auto0_0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec3_reload_addrfilt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec3.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2filt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2COEFF_auto_HALFBAND_CENTRE0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2COEFF_auto0_2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2COEFF_auto0_1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2COEFF_auto0_0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2_reload_addrfilt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1filt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto_HALFBAND_CENTRE0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto0_5.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto0_4.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto0_3.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto0_2.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto0_1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1COEFF_auto0_0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1_reload_addrfilt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbdec1.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3filt_decode_rom.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3COEFF_auto_HALFBAND_CENTRE0.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj

set file "coregen_dsp/hbint3COEFF_auto0_5.mif"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Memory Initialization Files" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "top" "x300_gpr" $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/axi/axi_chdr_tb.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/control/axi_crossbar/sim_2x2/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/control/axi_crossbar/sim_4x4/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/control/axi_crossbar/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/dsp/ddc_chain/dc_in_cordic_decim_2/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/dsp/ddc_chain/dc_in_cordic_decim_6/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/fifo/axi_dram_fifo/sim_sram_1/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/fifo/axi_dram_fifo/sim_sram_2/simulation_script.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/sim/packet_proc/eth_dispatch/simulation_script.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "top" "x300_gpr" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.unifast" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7k325tffg900-2" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7k325tffg900-2" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:project_gpr"
