#
# Vivado (TM) v2015.4 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'project_radar'
#
# Generated by Vivado on Wed Oct 26 22:58:24 PDT 2016
# IP Build 1412160 on Tue Nov 17 13:47:24 MST 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/ram_2port.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_short.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop2.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_bram.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_waveform_datamover/axi_waveform_datamover.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_parser.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/setting_reg.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_framer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/SP_DDS/SP_DDS.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/vita/packet_error_responder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/vita/flow_control_responder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_cascade.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/bram_stream_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/fifo_generator_adc/fifo_generator_adc.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/packet_proc/source_flow_control.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_responder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_fifo_large.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_packet_gate.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/waveform_stream.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/waveform_formatter.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/waveform_dds.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/timing/time_compare.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/simple_spi_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_crossclock.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/gpio_atr.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/chirpgen.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/adc_data_axis_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_encoder.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_output_port.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_input_port.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/cmd_pkt_proc.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_deframer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux4.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk_cascade.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux4.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/wavegen/wavegen_block.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/rx_command_gen.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_tx_controller.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_sample_synchronizer.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_rx_controller.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_pulse_controller.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/radio_core_regs.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/radio/db_control.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_packet_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/axi_delay_fifo.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/timing/timekeeper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell_regs.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_wrapper.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_core_regs.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_core.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/source/top/radar_block.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/axi_slave_mux.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/axi_forwarding_cam.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_block_export_io.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/control/axi_crossbar.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/rfnoc/data_types.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/task_library.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/rfnoc/sim_rfnoc_lib.svh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/general/sim_math.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/general/sim_file_io.svh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/general/sim_exec_report.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/general/sim_clks_rsts.vh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/control/sim_set_rb_lib.svh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/axi/sim_cvita_lib.svh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/axi/sim_axis_lib.svh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/axi/sim_axi4_lib.svh"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_4k_2clk/fifo_4k_2clk.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_short_2clk/fifo_short_2clk.upgrade_log"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/cmpy_16b/cmpy_16b.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_4k_2clk/fifo_4k_2clk.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_short_2clk/fifo_short_2clk.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/ip/axis_data_fifo_0/axis_data_fifo_0.xci"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/sim/radar_block/block_radar_core_tb/block_radar_core_tb.sv"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/sim/radar_block/block_radar_core_tb_behav.wcfg"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/sim/serial_to_settings/serial_settings_tasks.v"
#    "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/submodules/fpga/usrp3_rfnoc/lib/axi/axi_defs.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < [llength $::argc]} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir" { incr i; set origin_dir [lindex $::argv $i] }
      "--help"       { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project project_radar ./project_radar

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [get_projects project_radar]
set_property "board_part" "" $obj
set_property "compxlib.activehdl_compiled_library_dir" "$proj_dir/project_radar.cache/compile_simlib/activehdl" $obj
set_property "compxlib.funcsim" "1" $obj
set_property "compxlib.ies_compiled_library_dir" "$proj_dir/project_radar.cache/compile_simlib/ies" $obj
set_property "compxlib.modelsim_compiled_library_dir" "$proj_dir/project_radar.cache/compile_simlib/modelsim" $obj
set_property "compxlib.overwrite_libs" "0" $obj
set_property "compxlib.questa_compiled_library_dir" "$proj_dir/project_radar.cache/compile_simlib/questa" $obj
set_property "compxlib.riviera_compiled_library_dir" "$proj_dir/project_radar.cache/compile_simlib/riviera" $obj
set_property "compxlib.timesim" "1" $obj
set_property "compxlib.vcs_compiled_library_dir" "$proj_dir/project_radar.cache/compile_simlib/vcs" $obj
set_property "corecontainer.enable" "1" $obj
set_property "default_lib" "xil_defaultlib" $obj
set_property "enable_optional_runs_sta" "0" $obj
set_property "ip_cache_permissions" "" $obj
set_property "ip_output_repo" "" $obj
set_property "managed_ip" "0" $obj
set_property "part" "xc7k325tffg900-2" $obj
set_property "sim.ip.auto_export_scripts" "1" $obj
set_property "simulator_language" "Mixed" $obj
set_property "source_mgmt_mode" "All" $obj
set_property "target_language" "Verilog" $obj
set_property "target_simulator" "XSim" $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/ram_2port.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_short.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop2.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_flop.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_bram.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo.v"]"\
 "[file normalize "$origin_dir/../../ip/axi_waveform_datamover/axi_waveform_datamover.xci"]"\
 "[file normalize "$origin_dir/../../ip/axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_parser.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/setting_reg.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_framer.v"]"\
 "[file normalize "$origin_dir/../../ip/SP_DDS/SP_DDS.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/vita/packet_error_responder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/vita/flow_control_responder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_cascade.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/bram_stream_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk.v"]"\
 "[file normalize "$origin_dir/../../ip/fifo_generator_adc/fifo_generator_adc.xci"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/packet_proc/source_flow_control.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_responder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_fifo_large.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_packet_gate.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/waveform_stream.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/waveform_formatter.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/waveform_dds.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/timing/time_compare.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/simple_spi_core.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_crossclock.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/gpio_atr.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/chirpgen.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux.v"]"\
 "[file normalize "$origin_dir/../../source/top/adc_data_axis_wrapper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cvita_hdr_encoder.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_output_port.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_input_port.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/cmd_pkt_proc.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/chdr_deframer.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_mux4.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_fifo_2clk_cascade.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux4.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/fifo/axi_demux.v"]"\
 "[file normalize "$origin_dir/../../source/top/wavegen/wavegen_block.v"]"\
 "[file normalize "$origin_dir/../../source/top/rx_command_gen.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_tx_controller.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_sample_synchronizer.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_rx_controller.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_pulse_controller.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/radio_core_regs.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/radio/db_control.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_packet_mux.v"]"\
 "[file normalize "$origin_dir/../../source/top/axi_delay_fifo.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/timing/timekeeper.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/settings_bus_mux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell_regs.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_shell.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/axi_wrapper.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_core_regs.vh"]"\
 "[file normalize "$origin_dir/../../source/top/radar_core.v"]"\
 "[file normalize "$origin_dir/../../source/top/radar_block.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/axi_slave_mux.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/axi_forwarding_cam.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/noc_block_export_io.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/control/axi_crossbar.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/rfnoc/data_types.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/task_library.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/rfnoc/sim_rfnoc_lib.svh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/general/sim_math.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/general/sim_file_io.svh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/general/sim_exec_report.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/general/sim_clks_rsts.vh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/control/sim_set_rb_lib.svh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/axi/sim_cvita_lib.svh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/axi/sim_axis_lib.svh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/axi/sim_axi4_lib.svh"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_4k_2clk/fifo_4k_2clk.upgrade_log"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_short_2clk/fifo_short_2clk.upgrade_log"]"\
 "[file normalize "$origin_dir/../../ip/cmpy_16b/cmpy_16b.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "control/ram_2port.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_short.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_flop2.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_flop.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_bram.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "axi_waveform_datamover/axi_waveform_datamover.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "axi_waveform_bram_ctrl/axi_waveform_bram_ctrl.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/cvita_hdr_parser.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/setting_reg.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/chdr_framer.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "SP_DDS/SP_DDS.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "vita/packet_error_responder.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "vita/flow_control_responder.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_cascade.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "wavegen/bram_stream_wrapper.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_2clk.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo_generator_adc/fifo_generator_adc.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "packet_proc/source_flow_control.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/noc_responder.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/chdr_fifo_large.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_packet_gate.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "wavegen/waveform_stream.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "wavegen/waveform_formatter.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "wavegen/waveform_dds.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "timing/time_compare.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/simple_spi_core.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/settings_bus_crossclock.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/gpio_atr.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "wavegen/chirpgen.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_mux.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/adc_data_axis_wrapper.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/cvita_hdr_encoder.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/noc_output_port.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/noc_input_port.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/cmd_pkt_proc.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/chdr_deframer.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_mux4.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_fifo_2clk_cascade.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_demux4.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo/axi_demux.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "wavegen/wavegen_block.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/rx_command_gen.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_tx_controller.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_sample_synchronizer.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_rx_controller.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_pulse_controller.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "radio/radio_core_regs.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "radio/db_control.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/axi_packet_mux.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/axi_delay_fifo.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "timing/timekeeper.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/settings_bus_mux.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/noc_shell_regs.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/noc_shell.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/axi_wrapper.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_core_regs.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_core.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "top/radar_block.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/axi_slave_mux.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/axi_forwarding_cam.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/noc_block_export_io.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/axi_crossbar.v"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/data_types.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "sim/task_library.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "rfnoc/sim_rfnoc_lib.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "general/sim_math.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "general/sim_file_io.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "general/sim_exec_report.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "general/sim_clks_rsts.vh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "control/sim_set_rb_lib.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "axi/sim_cvita_lib.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "axi/sim_axis_lib.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "axi/sim_axi4_lib.svh"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "Verilog Header" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "fifo_4k_2clk/fifo_4k_2clk.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "" $file_obj

set file "fifo_short_2clk/fifo_short_2clk.upgrade_log"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property "file_type" "IP Update Log" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "" $file_obj

set file "cmpy_16b/cmpy_16b.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property "design_mode" "RTL" $obj
set_property "edif_extra_search_paths" "" $obj
set_property "elab_link_dcps" "1" $obj
set_property "elab_load_timing_constraints" "1" $obj
set_property "generic" "" $obj
set_property "include_dirs" "" $obj
set_property "lib_map_file" "" $obj
set_property "loop_count" "1000" $obj
set_property "name" "sources_1" $obj
set_property "top" "radar_block" $obj
set_property "verilog_define" "" $obj
set_property "verilog_uppercase" "0" $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_4k_2clk/fifo_4k_2clk.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_4k_2clk/fifo_4k_2clk.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/top/x300/ip/fifo_short_2clk/fifo_short_2clk.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "fifo_short_2clk/fifo_short_2clk.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj


# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 "[file normalize "$origin_dir/../../ip/axis_data_fifo_0/axis_data_fifo_0.xci"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "axis_data_fifo_0/axis_data_fifo_0.xci"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
if { ![get_property "is_locked" $file_obj] } {
  set_property "generate_synth_checkpoint" "1" $file_obj
}
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj


# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property "name" "constrs_1" $obj
set_property "target_constrs_file" "" $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 "[file normalize "$origin_dir/../../sim/radar_block/block_radar_core_tb/block_radar_core_tb.sv"]"\
 "[file normalize "$origin_dir/../../sim/radar_block/block_radar_core_tb_behav.wcfg"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/sim/serial_to_settings/serial_settings_tasks.v"]"\
 "[file normalize "$origin_dir/../../submodules/fpga/usrp3_rfnoc/lib/axi/axi_defs.v"]"\
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "block_radar_core_tb/block_radar_core_tb.sv"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "SystemVerilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "radar_block/block_radar_core_tb_behav.wcfg"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "simulation" $file_obj
set_property "used_in_simulation" "1" $file_obj

set file "serial_to_settings/serial_settings_tasks.v"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj

set file "axi/axi_defs.v"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property "file_type" "Verilog" $file_obj
set_property "is_enabled" "1" $file_obj
set_property "is_global_include" "0" $file_obj
set_property "library" "xil_defaultlib" $file_obj
set_property "path_mode" "RelativeFirst" $file_obj
set_property "used_in" "synthesis implementation simulation" $file_obj
set_property "used_in_implementation" "1" $file_obj
set_property "used_in_simulation" "1" $file_obj
set_property "used_in_synthesis" "1" $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property "generic" "" $obj
set_property "include_dirs" "" $obj
set_property "name" "sim_1" $obj
set_property "nl.cell" "" $obj
set_property "nl.incl_unisim_models" "0" $obj
set_property "nl.process_corner" "slow" $obj
set_property "nl.rename_top" "" $obj
set_property "nl.sdf_anno" "1" $obj
set_property "nl.write_all_overrides" "0" $obj
set_property "runtime" "1000ns" $obj
set_property "source_set" "sources_1" $obj
set_property "top" "block_radar_core_tb" $obj
set_property "unit_under_test" "" $obj
set_property "verilog_define" "" $obj
set_property "verilog_uppercase" "0" $obj
set_property "xelab.debug_level" "typical" $obj
set_property "xelab.dll" "0" $obj
set_property "xelab.load_glbl" "1" $obj
set_property "xelab.more_options" "" $obj
set_property "xelab.mt_level" "auto" $obj
set_property "xelab.nosort" "1" $obj
set_property "xelab.rangecheck" "0" $obj
set_property "xelab.relax" "1" $obj
set_property "xelab.sdf_delay" "sdfmax" $obj
set_property "xelab.snapshot" "" $obj
set_property "xelab.unifast" "" $obj
set_property "xsim.compile.xvhdl.more_options" "" $obj
set_property "xsim.compile.xvhdl.nosort" "1" $obj
set_property "xsim.compile.xvhdl.relax" "1" $obj
set_property "xsim.compile.xvlog.more_options" "" $obj
set_property "xsim.compile.xvlog.nosort" "1" $obj
set_property "xsim.compile.xvlog.relax" "1" $obj
set_property "xsim.elaborate.debug_level" "typical" $obj
set_property "xsim.elaborate.load_glbl" "1" $obj
set_property "xsim.elaborate.mt_level" "auto" $obj
set_property "xsim.elaborate.rangecheck" "0" $obj
set_property "xsim.elaborate.relax" "1" $obj
set_property "xsim.elaborate.sdf_delay" "sdfmax" $obj
set_property "xsim.elaborate.snapshot" "" $obj
set_property "xsim.elaborate.xelab.more_options" "" $obj
set_property "xsim.more_options" "" $obj
set_property "xsim.saif" "" $obj
set_property "xsim.simulate.runtime" "1000ns" $obj
set_property "xsim.simulate.saif" "" $obj
set_property "xsim.simulate.saif_all_signals" "0" $obj
set_property "xsim.simulate.uut" "" $obj
set_property "xsim.simulate.wdb" "" $obj
set_property "xsim.simulate.xsim.more_options" "" $obj
set_property "xsim.tclbatch" "" $obj
set_property "xsim.view" "/media/sf_VMLinux/Projects/UndergroundRadar/x300_GPR/Firmware/sim/radar_block/block_radar_core_tb_behav.wcfg" $obj
set_property "xsim.wdb" "" $obj

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "constrset" "constrs_1" $obj
set_property "description" "Vivado Synthesis Defaults" $obj
set_property "flow" "Vivado Synthesis 2015" $obj
set_property "name" "synth_1" $obj
set_property "needs_refresh" "0" $obj
set_property "part" "xc7k325tffg900-2" $obj
set_property "srcset" "sources_1" $obj
set_property "strategy" "Vivado Synthesis Defaults" $obj
set_property "incremental_checkpoint" "" $obj
set_property "include_in_archive" "1" $obj
set_property "steps.synth_design.tcl.pre" "" $obj
set_property "steps.synth_design.tcl.post" "" $obj
set_property "steps.synth_design.args.flatten_hierarchy" "rebuilt" $obj
set_property "steps.synth_design.args.gated_clock_conversion" "off" $obj
set_property "steps.synth_design.args.bufg" "12" $obj
set_property "steps.synth_design.args.fanout_limit" "10000" $obj
set_property "steps.synth_design.args.directive" "Default" $obj
set_property "steps.synth_design.args.fsm_extraction" "auto" $obj
set_property "steps.synth_design.args.keep_equivalent_registers" "0" $obj
set_property "steps.synth_design.args.resource_sharing" "auto" $obj
set_property "steps.synth_design.args.control_set_opt_threshold" "auto" $obj
set_property "steps.synth_design.args.no_lc" "0" $obj
set_property "steps.synth_design.args.shreg_min_size" "3" $obj
set_property "steps.synth_design.args.max_bram" "-1" $obj
set_property "steps.synth_design.args.max_dsp" "-1" $obj
set_property "steps.synth_design.args.cascade_dsp" "auto" $obj
set_property -name {steps.synth_design.args.more options} -value {} -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "constrset" "constrs_1" $obj
set_property "description" "Vivado Implementation Defaults" $obj
set_property "flow" "Vivado Implementation 2015" $obj
set_property "name" "impl_1" $obj
set_property "needs_refresh" "0" $obj
set_property "part" "xc7k325tffg900-2" $obj
set_property "srcset" "sources_1" $obj
set_property "strategy" "Vivado Implementation Defaults" $obj
set_property "incremental_checkpoint" "" $obj
set_property "include_in_archive" "1" $obj
set_property "steps.opt_design.is_enabled" "1" $obj
set_property "steps.opt_design.tcl.pre" "" $obj
set_property "steps.opt_design.tcl.post" "" $obj
set_property "steps.opt_design.args.verbose" "0" $obj
set_property "steps.opt_design.args.directive" "Default" $obj
set_property -name {steps.opt_design.args.more options} -value {} -objects $obj
set_property "steps.power_opt_design.is_enabled" "0" $obj
set_property "steps.power_opt_design.tcl.pre" "" $obj
set_property "steps.power_opt_design.tcl.post" "" $obj
set_property -name {steps.power_opt_design.args.more options} -value {} -objects $obj
set_property "steps.place_design.tcl.pre" "" $obj
set_property "steps.place_design.tcl.post" "" $obj
set_property "steps.place_design.args.directive" "Default" $obj
set_property -name {steps.place_design.args.more options} -value {} -objects $obj
set_property "steps.post_place_power_opt_design.is_enabled" "0" $obj
set_property "steps.post_place_power_opt_design.tcl.pre" "" $obj
set_property "steps.post_place_power_opt_design.tcl.post" "" $obj
set_property -name {steps.post_place_power_opt_design.args.more options} -value {} -objects $obj
set_property "steps.phys_opt_design.is_enabled" "0" $obj
set_property "steps.phys_opt_design.tcl.pre" "" $obj
set_property "steps.phys_opt_design.tcl.post" "" $obj
set_property "steps.phys_opt_design.args.directive" "Default" $obj
set_property -name {steps.phys_opt_design.args.more options} -value {} -objects $obj
set_property "steps.route_design.tcl.pre" "" $obj
set_property "steps.route_design.tcl.post" "" $obj
set_property "steps.route_design.args.directive" "Default" $obj
set_property -name {steps.route_design.args.more options} -value {} -objects $obj
set_property "steps.post_route_phys_opt_design.is_enabled" "0" $obj
set_property "steps.post_route_phys_opt_design.tcl.pre" "" $obj
set_property "steps.post_route_phys_opt_design.tcl.post" "" $obj
set_property "steps.post_route_phys_opt_design.args.directive" "Default" $obj
set_property -name {steps.post_route_phys_opt_design.args.more options} -value {} -objects $obj
set_property "steps.write_bitstream.tcl.pre" "" $obj
set_property "steps.write_bitstream.tcl.post" "" $obj
set_property "steps.write_bitstream.args.raw_bitfile" "0" $obj
set_property "steps.write_bitstream.args.mask_file" "0" $obj
set_property "steps.write_bitstream.args.no_binary_bitfile" "0" $obj
set_property "steps.write_bitstream.args.bin_file" "0" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.logic_location_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj
set_property -name {steps.write_bitstream.args.more options} -value {} -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:project_radar"
